image:
  repository: minha-api   # << usa a imagem local que você buildou
  tag: "local"
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources: {}

env: []

ingress:
  enabled: true
  className: nginx
  host: minha-api.local
  path: /
