name: Trivy Security Scans

on:
  pull_request:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write

jobs:
  trivy-scans:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Cache do DB do Trivy (acelera execuções seguintes)
      - name: Cache Trivy DB
        uses: actions/cache@v4
        with:
          path: ~/.cache/trivy
          key: trivy-db-${{ runner.os }}-${{ hashFiles('**/lockfiles-go-here-if-any') }}
          restore-keys: |
            trivy-db-${{ runner.os }}-

      - name: Install Trivy
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      # 1) Dockerfile — misconfig (config scan) → SARIF
      - name: Trivy Dockerfile (misconfig)
        run: |
          trivy config --format sarif --output trivy-dockerfile.sarif Dockerfile || true

      - name: Upload SARIF (Dockerfile)
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-dockerfile.sarif
          category: trivy-dockerfile   # categoria única

      # 2) Filesystem do repo → vuln/secret/misconfig → SARIF
      - name: Trivy Filesystem (repo)
        run: |
          trivy fs --scanners vuln,secret,misconfig \
            --format sarif --output trivy-fs.sarif . || true

      - name: Upload SARIF (Filesystem)
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-fs.sarif
          category: trivy-fs          # categoria única

      # 3) Build da imagem local (para escanear CVEs na imagem)
      - name: Build image (local only)
        run: |
          IMAGE="ghcr.io/${{ github.repository_owner }}/minha-api:trivy-${{ github.sha }}"
          docker build -t "$IMAGE" .

      # 3a) Image scan (vuln/misconfig/secret) → SARIF
      - name: Trivy Image (vuln+misconfig+secret)
        id: trivy_image
        continue-on-error: true   # não interrompe antes do upload
        run: |
          IMAGE="ghcr.io/${{ github.repository_owner }}/minha-api:trivy-${{ github.sha }}"
          trivy image --scanners vuln,misconfig,secret \
            --severity HIGH,CRITICAL \
            --format sarif --output trivy-image.sarif "$IMAGE"
          # Resumo em texto (opcional)
          trivy image --scanners vuln --severity HIGH,CRITICAL --format table "$IMAGE" | tee trivy-image.txt

      - name: Upload SARIF (Image)
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-image.sarif
          category: trivy-image       # categoria única

      # (Opcional) resumo no Job
      - name: Summary (Image scan)
        if: always()
        run: |
          echo '### Trivy Image (HIGH/CRITICAL) Summary' >> $GITHUB_STEP_SUMMARY
          echo '' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat trivy-image.txt >> $GITHUB_STEP_SUMMARY || true
          echo '```' >> $GITHUB_STEP_SUMMARY

      # 4) Gate de PR: falha somente em pull_request se houver HIGH/CRITICAL na imagem
      - name: Enforce on PRs (fail if HIGH/CRITICAL on image)
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          IMAGE="ghcr.io/${{ github.repository_owner }}/minha-api:trivy-${{ github.sha }}"
          trivy image --scanners vuln --severity HIGH,CRITICAL --exit-code 1 "$IMAGE"
